### ISSUE TITLE
(비공식) 프로그래머스 동적계획법

### ISSUE THREAD

**Issue by blcklamb** [blcklamb/elice-02-study-01-algorithm#18]
🍕(4월 24일) 1. N으로 표현
https://programmers.co.kr/learn/courses/30/lessons/42895

    🍕(5월 1일) 2. 정수 삼각형
https://programmers.co.kr/learn/courses/30/lessons/43105

**Comment by seogudwns** [comment]
4/24 8번케이스에서 막힘
5/1 20분만에 solve.,,,,,,,
