### ISSUE TITLE
(3주차) 엘리스 큐

### ISSUE THREAD

**Issue by blcklamb** [blcklamb/elice-02-study-01-algorithm#19]
![image](https://user-images.githubusercontent.com/92101831/163508907-85ab4651-a98e-4230-b58a-83164fab55a8.png)

다음 공식 모임인 5월 10일까지 해당 강의를 수강하고 오세요!

강의에 관련된 의견/질문 등은 댓글로 남겨주세요

**Comment by seogudwns** [comment]
![스크린샷(132)](https://user-images.githubusercontent.com/38065726/167395765-02db099c-4ec1-46e8-a2d5-8c24759b2983.png)

**Comment by blcklamb** [comment]
![image](https://user-images.githubusercontent.com/92101831/167461056-65ee9666-20b8-4032-9325-59acef5c6dc6.png)

**Comment by eikjae** [comment]
![image](https://user-images.githubusercontent.com/77964128/167617816-1192d0a0-56c8-419b-9787-5ef4def006b3.png)

**Comment by JiwooAn** [comment]
![image](https://user-images.githubusercontent.com/97489259/167618006-db3e67e8-c916-4feb-80c8-1d1340260bbd.png)

**Comment by KwanHoo** [comment]
![화면 캡처 2022-05-10 203400](https://user-images.githubusercontent.com/49335804/167619514-0a4f3ca6-e6cd-4e54-a14b-6d8f4afb65e7.png)
