### ISSUE TITLE
(1주차) 공통 문제

### ISSUE THREAD

**Issue by blcklamb** [blcklamb/elice-02-study-01-algorithm#2]
[자리수의 제곱](https://www.acmicpc.net/problem/4881
)
[로봇 청소기](https://www.acmicpc.net/problem/14503)

댓글로 자유롭게 여러분의 의견을 남겨주세요.

ex. 앗싸 다 풀었다.
ex. ~번 문제 메모리 초과가 떠서 못 풀었어요.
ex. 밤샘 각이에요.

**Comment by seogudwns** [comment]
자리수의 제곱. done
로봇청소기. 알고리즘에 대한 이해가 머릿속에 입력이 안되고 있어서 겁나 해매는중..,,,ㄷㄷㄷㄷㄷ

**Comment by blcklamb** [comment]
로봇청소기 백준 페이지 광고에 로봇청소기 나오는 거 제법 열받아요

![image](https://user-images.githubusercontent.com/92101831/161561658-4ab108b4-0322-4e84-bdc9-867448c6a6fa.png)
