### ISSUE TITLE
(4주차) 엘리스 그래프 알고리즘

### ISSUE THREAD

**Issue by blcklamb** [blcklamb/elice-02-study-01-algorithm#23]
5월 17일까지 해당 강의를 수강하고 오시길 바랍니다!

강의 수강 시 진도율 캡쳐를 댓글로 남겨주세요.

![image](https://user-images.githubusercontent.com/92101831/168195903-6f1858f0-cd9a-4f8c-8c07-d1b8819cd2be.png)

**Comment by s0n9h2** [comment]
![image](https://user-images.githubusercontent.com/50363255/168792818-648f01dc-1502-4cf5-9522-971adf9f1243.png)
엘리스는 왜 입력 형식과 solution 함수에 들어가 있는 매개변수가 이상하게 달라서
문제를 풀어볼 의욕이 안나게 하네요...

**Comment by eikjae** [comment]
![image](https://user-images.githubusercontent.com/77964128/168805363-3959636f-81c4-47ac-83d1-c6c4ca202dc8.png)
