### ISSUE TITLE
(1주차) 엘리스 분할 정복법

### ISSUE THREAD

**Issue by blcklamb** [blcklamb/elice-02-study-01-algorithm#3]
![image](https://user-images.githubusercontent.com/92101831/161184863-a99ccfd0-4928-4085-8882-ccb993e0d57d.png)

수강 이후 과목 진도율 캡쳐를 댓글로 남겨주세요!

**Comment by JiwooAn** [comment]
![image](https://user-images.githubusercontent.com/97489259/161527427-34407856-b180-458f-956e-61ce7029aa50.png)

**Comment by seogudwns** [comment]
![스크린샷(75)](https://user-images.githubusercontent.com/38065726/161536230-d454ec59-fb68-4cb5-a31b-fac4bec68c74.png)

**Comment by blcklamb** [comment]
![image](https://user-images.githubusercontent.com/92101831/161537561-67c54256-c427-44a8-aa46-92c43770550e.png)

혹시 여기 오답 처리하신 분 있나요?

**Comment by JiwooAn** [comment]
left, right할 때 `in arr` 이 아니라 `in arr[1:]`로 하면 잘 돼요!

**Comment by seogudwns** [comment]
이유 : 정렬할 때 pivot을 빼야하니까요..ㅎㅎ

 + 이거 알람에 손이 잘 닿지가 않는군요 ㄷㄷ.. github을 쓰기 편한 방법이 있으려나요?

**Comment by blcklamb** [comment]
![image](https://user-images.githubusercontent.com/92101831/161547617-6395b1a7-9a41-4378-8fca-ce689924b101.png)

앗싸 이제 공통문제 풀러갑니당

**Comment by blcklamb** [comment]
> 이유 : 정렬할 때 pivot을 빼야하니까요..ㅎㅎ
> 
> * 이거 알람에 손이 잘 닿지가 않는군요 ㄷㄷ.. github을 쓰기 편한 방법이 있으려나요?

알람에 손이 닿지 않는다는 게 무슨 의미인가용? 알람이 안 간다는 의미인가요?

**Comment by seogudwns** [comment]
음... 디코에 비해 뭔가 불편하다? 그런건데 어떻게 설명해야할지 모르겠네요..ㅎㅎ;
그냥 적응해봐야겠어요.

**Comment by eikjae** [comment]
<img width="840" alt="캡처" src="https://user-images.githubusercontent.com/77964128/161568550-27ff4beb-7786-4f94-a109-1d73aaaa9322.PNG">

**Comment by KwanHoo** [comment]
![elice](https://user-images.githubusercontent.com/49335804/161690146-65f9bf41-fd5e-43fc-b245-4239d94e9ef5.png)

**Comment by s0n9h2** [comment]
![image](https://user-images.githubusercontent.com/50363255/161733293-12024343-da9b-475f-8495-ff8a3973bc85.png)
자꾸 이상한데서 헤매다가 늦었습니다😥 죄송해요.. 5시간....ㅂㄷ... 제가 부족한 탓이겠죠ㅠㅠ

**Comment by blcklamb** [comment]
> ![image](https://user-images.githubusercontent.com/50363255/161733293-12024343-da9b-475f-8495-ff8a3973bc85.png) 자꾸 이상한데서 헤매다가 늦었습니다😥 죄송해요.. 5시간....ㅂㄷ... 제가 부족한 탓이겠죠ㅠㅠ

전혀 부족하지 않아도 송희넴~ 수고하셨습니다!!
