### ISSUE TITLE
(1주차) 엘리스 재귀 호출

### ISSUE THREAD

**Issue by blcklamb** [blcklamb/elice-02-study-01-algorithm#6]
![image](https://user-images.githubusercontent.com/92101831/161765910-ee0a394b-6b19-4665-9c33-315884a7894e.png)

다음 엘리스 강의 예습 겸 분할정복법 문제 풀이 대비 겸 

'재귀 호출' 강의를 들으면 댓글로 진도율 캡쳐를 남겨주세요.

더불어 질문과 제안은 언제든 남겨주세요!

필수가 아니라 선택이니 하고 싶지 않은 분들께선 assignees에서 선택 해제 해주세요!

**Comment by seogudwns** [comment]
![스크린샷(79)](https://user-images.githubusercontent.com/38065726/161979999-d1c571c6-ccc5-4844-97c1-0bab4d74f39b.png)

쉽다해서 편안하게 보니 18분...ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ

**Comment by eikjae** [comment]
<img width="746" alt="캡처" src="https://user-images.githubusercontent.com/77964128/162190663-d47cd587-2ec1-47d1-8244-265aa42a94e7.PNG">
재귀 호출 진도율 캡처입니다!
